@startuml

title __SEMANTIC's Class Diagram__\n

  namespace  {
    namespace om.upf.nli.analyzer.semantic_analyzer {
      namespace repository {
        namespace semantic {
          interface com.upf.nli.analyzer.semantic_analyzer.repository.semantic.CourseRepository {
              {abstract} + findAllByTeacher()
              {abstract} + findByName()
              {abstract} + findByNameContaining()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace om.upf.nli.analyzer.semantic_analyzer {
      namespace repository {
        namespace semantic {
          interface com.upf.nli.analyzer.semantic_analyzer.repository.semantic.LibraryRepository {
              {abstract} + findByName()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace om.upf.nli.analyzer.semantic_analyzer {
      namespace repository {
        namespace semantic {
          interface com.upf.nli.analyzer.semantic_analyzer.repository.semantic.ProgrammeRepository {
              {abstract} + findByName()
              {abstract} + findByNameContaining()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace om.upf.nli.analyzer.semantic_analyzer {
      namespace repository {
        namespace semantic {
          interface com.upf.nli.analyzer.semantic_analyzer.repository.semantic.TeacherRepository {
              {abstract} + findByCourses_NameContaining()
              {abstract} + findByName()
              {abstract} + findByNameContaining()
          }
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
